export const ACCOUNT_FETCH = 'ACCOUNT_FETCH'
export const ACCOUNT_SAVE_PENDING = 'ACCOUNT_SAVE_PENDING'
export const ACCOUNT_SAVE_FULFILLED = 'ACCOUNT_SAVE_FULFILLED'
export const ACCOUNT_SAVE_REJECTED = 'ACCOUNT_SAVE_REJECTED'

export const AUTH_CLEAR = 'AUTH_CLEAR'
export const AUTH_SET_ERROR = 'AUTH_SET_ERROR'
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN'
export const AUTH_SET_USER = 'AUTH_SET_USER'

export const PAGE_SET = 'PAGE_SET'

export const POST_CREATE = 'POST_CREATE'
export const POST_DELETE = 'POST_DELETE'
export const POST_FETCH = 'POST_FETCH'
export const POST_LIKE = 'POST_LIKE'
export const POST_UNLIKE = 'POST_UNLIKE'

export const POSTS_FETCH = 'POSTS_FETCH'

export const USER_FETCH = 'USER_FETCH'
export const USER_FOLLOW = 'USER_FOLLOW'
export const USER_UNFOLLOW = 'USER_UNFOLLOW'

export const USERS_FETCH_PENDING = 'USERS_FETCH_PENDING'
export const USERS_FETCH_FULFILLED = 'USERS_FETCH_FULFILLED'
export const USERS_FETCH_REJECTED = 'USERS_FETCH_REJECTED'
