export const ACCOUNT_FETCH = 'ACCOUNT/FETCH'
export const ACCOUNT_SAVE_PENDING = 'ACCOUNT/SAVE_PENDING'
export const ACCOUNT_SAVE_FULFILLED = 'ACCOUNT/SAVE_FULFILLED'
export const ACCOUNT_SAVE_REJECTED = 'ACCOUNT/SAVE_REJECTED'

export const AUTH_CLEAR = 'AUTH/CLEAR'
export const AUTH_SET_AUTHENTICATED = 'AUTH/SET_AUTHENTICATED'
export const AUTH_SET_ERROR = 'AUTH/SET_ERROR'

export const POST_COMMENT = 'POST/COMMENT'
export const POST_CREATE = 'POST/CREATE'
export const POST_DELETE = 'POST/DELETE'
export const POST_LIKE = 'POST/LIKE'
export const POST_SAVE = 'POST/SAVE'
export const POST_UNLIKE = 'POST/UNLIKE'

export const POSTS_FETCH = 'POSTS/FETCH'

export const TIMELINES_REMOVE_POST = 'TIMELINES/REMOVE_POST'
export const TIMELINES_SET_POSTS = 'TIMELINES/SET_POSTS'
export const TIMELINES_TOGGLE_HAS_MORE = 'TIMELINES/TOGGLE_HAS_MORE'

export const USER_FETCH = 'USER/FETCH'
export const USER_FOLLOW = 'USER/FOLLOW'
export const USER_UNFOLLOW = 'USER/UNFOLLOW'

export const USERS_FETCH_PENDING = 'USERS/FETCH_PENDING'
export const USERS_FETCH_FULFILLED = 'USERS/FETCH_FULFILLED'
export const USERS_FETCH_REJECTED = 'USERS/FETCH_REJECTED'
